apiVersion: v1
kind: Secret
metadata:
  name: fiap-soat-produtos-secrets
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-produtos
    service: produtos
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_KEY"
  AWS_SESSION_TOKEN: "YOUR_AWS_SESSION_TOKEN"
